In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
A[0]

array([1, 2, 3])

In [6]:
A[:,1]

array([2, 5, 8])